name: Add APK version to release notes

on:
  release:
    push:
      types:
      - created
      - edited
      - published
      
permissions:
  contents: write

jobs:
  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download APK
        run: |
          apk_url=$(curl https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets | jq -r '.[] | select(.name=="app-release.apk") | .browser_download_url')
          curl -L -o app-release.apk ${apk_url}

      - name: Extract versionCode and versionName from APK
        run: |
          sudo apt-get install -y aapt
          version_code=$(aapt dump badging app-release.apk | grep -oP "versionCode='\\d+'" | cut -d"'" -f2)
          version_name=$(aapt dump badging app-release.apk | grep -oP "versionName='.+'" | cut -d"'" -f2)          
          echo "{ \"version\": { \"code\": ${version_code}, \"name\": \"${version_name}\" }, \"apks\": { \"default\": \"app-release.apk\" } }" > app-release-data.json

      - name: Add release data file to release
        uses: softprops/action-gh-release@v1
        with:
            files: ./app-release-data.json
            token: ${{ secrets.GITHUB_TOKEN }}
